[package]
name = "actix-api"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
dotenv = "0.15.0"
futures = "0.3.25"
log = "0.4.17"
log4rs = "1.2.0"
mongodb = "2.3.1"
nanoid = "0.4.0"
serde = "1.0.151"
serde_json = "1.0.91"
