[package]
name = "actix-api"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = "0.4"
dotenv = "0.15"
futures = "0.3"
log = "0.4"
log4rs = "1"
mongodb = "2"
nanoid = "0.4"
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }
